USE [master]
GO

/****** Object:  Database [PixelGem]    Script Date: 26/04/2024 14:46:25 ******/
CREATE DATABASE [PixelGem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PixelGem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PixelGem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PixelGem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PixelGem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PixelGem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PixelGem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PixelGem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PixelGem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PixelGem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PixelGem] SET ARITHABORT OFF 
GO

ALTER DATABASE [PixelGem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PixelGem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PixelGem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PixelGem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PixelGem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PixelGem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PixelGem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PixelGem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PixelGem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PixelGem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PixelGem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PixelGem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PixelGem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PixelGem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PixelGem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PixelGem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PixelGem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PixelGem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PixelGem] SET  MULTI_USER 
GO

ALTER DATABASE [PixelGem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PixelGem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PixelGem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PixelGem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PixelGem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PixelGem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PixelGem] SET QUERY_STORE = ON
GO

ALTER DATABASE [PixelGem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PixelGem] SET  READ_WRITE 
GO


USE [PixelGem]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Categories](
	[IdCategory] [int] IDENTITY(1,1) NOT NULL,
	[ProductCategory] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[IdCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Products](
	[IdProduct] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Image] [nvarchar](max) NULL,
	[Stock] [int] NOT NULL,
	[IdCategory] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[DiscountPercentage] [int] NULL,
	[AverageRating] [decimal](2, 1) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[IdProduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY([IdCategory])
REFERENCES [dbo].[Categories] ([IdCategory])
GO

ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories]
GO

CREATE TABLE [dbo].[CartItems](
	[IdCartItem] [int] IDENTITY(1,1) NOT NULL,
	[IdCart] [int] NOT NULL,
	[IdProduct] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_CartItems] PRIMARY KEY CLUSTERED 
(
	[IdCartItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CartItems]  WITH CHECK ADD  CONSTRAINT [FK_CartItems_Carts] FOREIGN KEY([IdCart])
REFERENCES [dbo].[Carts] ([IdCart])
GO

ALTER TABLE [dbo].[CartItems] CHECK CONSTRAINT [FK_CartItems_Carts]
GO

ALTER TABLE [dbo].[CartItems]  WITH CHECK ADD  CONSTRAINT [FK_CartItems_Products] FOREIGN KEY([IdProduct])
REFERENCES [dbo].[Products] ([IdProduct])
GO

ALTER TABLE [dbo].[CartItems] CHECK CONSTRAINT [FK_CartItems_Products]
GO

CREATE TABLE [dbo].[Carts](
	[IdCart] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL,
 CONSTRAINT [PK_Carts] PRIMARY KEY CLUSTERED 
(
	[IdCart] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Carts]  WITH CHECK ADD  CONSTRAINT [FK_Carts_Users] FOREIGN KEY([IdUser])
REFERENCES [dbo].[Users] ([IdUser])
GO

ALTER TABLE [dbo].[Carts] CHECK CONSTRAINT [FK_Carts_Users]
GO

CREATE TABLE [dbo].[Users](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](20) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Role] [nvarchar](10) NOT NULL,
	[FirstName] [nvarchar](20) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[Phone] [varchar](20) NULL,
	[Address] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Orders](
	[IdOrder] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL,
	[DateOrder] [datetime] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[IdOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Users] FOREIGN KEY([IdUser])
REFERENCES [dbo].[Users] ([IdUser])
GO

ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Users]
GO

CREATE TABLE [dbo].[OrderDetails](
	[IdOrderDetails] [int] IDENTITY(1,1) NOT NULL,
	[IdProduct] [int] NOT NULL,
	[IdOrder] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[ProductName] [nvarchar](50) NOT NULL,
	[ProductImage] [nvarchar](50) NULL,
	[ProductPrice] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED 
(
	[IdOrderDetails] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Orders] FOREIGN KEY([IdOrder])
REFERENCES [dbo].[Orders] ([IdOrder])
GO

ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_Orders]
GO

ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Products] FOREIGN KEY([IdProduct])
REFERENCES [dbo].[Products] ([IdProduct])
GO

ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_Products]
GO

CREATE TABLE [dbo].[Reviews](
	[IdReview] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL,
	[Rate] [decimal](2, 1) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[IdProduct] [int] NOT NULL,
 CONSTRAINT [PK_Reviews] PRIMARY KEY CLUSTERED 
(
	[IdReview] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD  CONSTRAINT [FK_Reviews_Products] FOREIGN KEY([IdProduct])
REFERENCES [dbo].[Products] ([IdProduct])
GO

ALTER TABLE [dbo].[Reviews] CHECK CONSTRAINT [FK_Reviews_Products]
GO

ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD  CONSTRAINT [FK_Reviews_Users] FOREIGN KEY([IdUser])
REFERENCES [dbo].[Users] ([IdUser])
GO

ALTER TABLE [dbo].[Reviews] CHECK CONSTRAINT [FK_Reviews_Users]
GO
